# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or.create alongside the database with db:setup).
#
# Examples:
#
#   movMovie.create[{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.createname: "Luke", movie: movies.first)

Plant.destroy_all
User.destroy_all
Garden.destroy_all
Text.destroy_all


puts "Seeding plants...🌱"

Plant.create(name: "Airplant", scientific_name: "Tillandsia", family: "bromeliaceae", light_level: "bright", light_position: "indirect", size: "small", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/airplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887290", water_interval: 12, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Burro's Tail", scientific_name: "Sedum morganianum", family: "succulent", light_level: "low", light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/burrowstail.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390873933", water_interval:  12, rotate_interval: 0, soil_interval:  0)
Plant.create(name: "Cast Iron Plant", scientific_name: "Aspidistra elatior", family: "asparagaceae", light_level: "low",light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Cast_Iron_Plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875830", water_interval:  6, rotate_interval: 0, soil_interval:  0)
Plant.create(name: "China Doll Plant", scientific_name: "Radermachera sinica", family: "evergreen", light_level: "low", light_position: "indirect", size: "small", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/chinadoll.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390877939", water_interval:  6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Chinese Croton", scientific_name: "Excoecaria cochinchinensis", family: "euphorbias", light_level: "medium", light_position: "indirect", size: "large", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/chinesecroton.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390886908", water_interval:  6, rotate_interval: 6, soil_interval: 30)
Plant.create(name: "Corn Plant", scientific_name: "Dracaena fragrans", family: "asparagaceae,", light_level: "medium" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Corn_Plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390874676", water_interval:  6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Creeping Fig", scientific_name: "Ficus pumila", family: "ficus", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Cast_Iron_Plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875830", water_interval:  6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Gold Dust Croton", scientific_name: "Codiaeum variegatum", family: "euphorbiaceae", light_level: "low" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Gold_Dust_Croton.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879686", water_interval:  6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Dragon Tree", scientific_name: "Dracaena marginata", family: "asparagaceae", light_level: "low" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/dragontree.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879250", water_interval:  6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Dumb Cane", scientific_name: "Dieffenbachia", family: "araceae", light_level: "bright" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/dumbcane.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390874927", water_interval:  3, rotate_interval: 7, soil_interval: 30)
Plant.create(name: "Elephant Ear", scientific_name: "Caladium", family: "araceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/elephantear.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390878352", water_interval: 3, rotate_interval: 7, soil_interval: 30)
Plant.create(name: "Emerald Gem", scientific_name: "Homalomena", family: "araceae", light_level: "low" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/emeraldgem.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876244", water_interval:  6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Emerald Ripple Peperomia", scientific_name: "Peperomia caperata", family: "piperaceae", light_level: "bright" , light_position: "indirect", size: "moderate", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/emeraldripple.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390877568", water_interval:  9, rotate_interval: 9, soil_interval: 0)
Plant.create(name: "Snake Plant", scientific_name: "Aglaonema", family: "araceae", light_level: "medium" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/snakeplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876407", water_interval:  12, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Eucalyptus", scientific_name: "Eucalyptus globulus", family: "aromatic", light_level: "low" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/eucalyptus.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390888612", water_interval: 12, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Fiddle Leaf Fig", scientific_name: "Ficus lyrata", family: "ficus", light_level: "bright" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Fiddle_Leaf_Fig.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390885484", water_interval: 12, rotate_interval: 12, soil_interval: 30)
Plant.create(name: "Fishbone Cactus", scientific_name: "Disocactus anguliger", family: "cactaceae", light_level: "low" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Fishbone_Cactus.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875112", water_interval:  15, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Fishtail Palm", scientific_name: "Caryota mitis", family: "arecaceae", light_level: "bright" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/fishtalepalm.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882065", water_interval:  6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Fizzle Sizzle", scientific_name: "Albuca spiralis", family: "araceae", light_level: "bright" , light_position: "direct", size: "large", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/fizzlesizzle.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390883537", water_interval:  10, rotate_interval: 10, soil_interval: 0)
Plant.create(name: "Heart Leaf fern", scientific_name: "Hemionitis arifolia", family: "fern", light_level: "medium" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/heartleaffern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390877367", water_interval:  10, rotate_interval: 10, soil_interval: 0)
Plant.create(name: "Inchplant", scientific_name: "Tradescantia", family: "succulent", light_level: "medium" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/inchplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390883750", water_interval:  15, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Jade Plant", scientific_name: "Crassula ovata", family: "succulent", light_level: "medium" , light_position: "direct", size: "medium", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/jadeplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887543", water_interval:  15, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Lucky Bamboo", scientific_name: "Dracaena sanderiana", family: "asparagaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/luckybamboo.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390874438", water_interval: 10, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Maidenhair", scientific_name: "Adiantum", family: "fern", light_level: "medium" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/maidenhair.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390886631", water_interval: 3, rotate_interval: 7, soil_interval: 0)
Plant.create(name: "Money Tree", scientific_name: "Pachira aquatica", family: "malvaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Moneytree.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390880925", water_interval: 12, rotate_interval: 12, soil_interval: 30)
Plant.create(name: "Nerve Plant", scientific_name: "Fittonia albivenis", family:"acanthaceae", light_level: "low" , light_position: "direct", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/nerveplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390888722", water_interval:  3, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Paddle Plant", scientific_name: "Kalanchoe thyrsiflora", family: "succulent", light_level: "bright" , light_position: "direct", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/paddleplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390873861", water_interval:  6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Parlor Palm", scientific_name: "Chamaedorea elegans", family: "arecaceae", light_level: "medium" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Parlorpalm.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390890058", water_interval:  6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Peace Lily", scientific_name: "Pilea involucrata", family: "araceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/peacelily.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390881652", water_interval: 6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Peacock Plant", scientific_name: "Calathea makoyana", family: "marantaceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/peacockplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390885037", water_interval: 3, rotate_interval:  0, soil_interval: 0)
Plant.create(name: "Persian shield", scientific_name: "Stobilanthes dyerianus", family: "acanthaceae", light_level: "bright" , light_position: "direct", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/persiansheild.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390885802", water_interval:  3, rotate_interval: 7, soil_interval: 0)
Plant.create(name: "Philodendron", scientific_name: "Pilea involucrata", family: "araceae", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/philodendron.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887571", water_interval: 6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Polka Dot Begonia", scientific_name: "Begonia maculata", family: "begoniaceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Polka_Dot_Begonia.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390881610", water_interval: 6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Ponytail Palm", scientific_name: "Beaucarnea Recurvata", family: "asparagaceae", light_level: "bright" , light_position: "direct", size: "large", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/ponytailpalm.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390874575", water_interval: 15, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Pothos", scientific_name: "Epipremnum aureum", family: "araceae", light_level: "bright" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/pothos.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887736", water_interval:  6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Prayer Plant", scientific_name: "Oxalis", family: "oxalidaceae", light_level: "medium" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/prayerplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390889578", water_interval: 6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Purple Shamrock", scientific_name: "Pilea involucrata", family: "urticaceae", light_level: "medium" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/purpleshamrock.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675394814490", water_interval: 15, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Rabbit's Foot Fern", scientific_name: "Davallia fejeensis", family: "fern", light_level: "bright" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/rabbitsfootfern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876158", water_interval: 10, rotate_interval: 10, soil_interval: 0)
Plant.create(name: "Red Aglaonema", scientific_name: " Aglaonema commutatum", family: "araceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Red_Aglaonema.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390888161", water_interval: 7, rotate_interval: 15, soil_interval: 0)
Plant.create(name: "Silver Dollar Vine", scientific_name: "Xerosicyos danguyi", family: "succulent", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/silverdollarvine.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675394814090", water_interval: 6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Spider Plant", scientific_name: "Chlorophytum comosum", family: "asparagaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/spiderplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876846", water_interval: 6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Shingle Plant", scientific_name: "Rhaphidophora hayi", family: "araceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/shingleplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390890147", water_interval: 3, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Staghorn Fern", scientific_name: "Platycerium ", family: "polypodiaceae", light_level: "bright" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/staghornfern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390884256", water_interval: 6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "String of Bananas", scientific_name: "Curio radicans", family: "succulent", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/stringofbananas.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390881107", water_interval: 12, rotate_interval: 12, soil_interval: 0)
Plant.create(name: "String of Dolphins", scientific_name: "Senecio peregrinus", family: "succulent", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/stringofdolphins.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879959", water_interval: 12, rotate_interval: 12, soil_interval: 0)
Plant.create(name: "String of Pearls", scientific_name: "Senecio rowleyanus", family: "succulent", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Stringofpearls.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390890401", water_interval: 12, rotate_interval: 12, soil_interval: 0)
Plant.create(name: "String of Turtles", scientific_name: "Peperomia prostrata", family: "succulent", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/stringofturtles.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887425", water_interval: 12, rotate_interval: 12, soil_interval: 0)
Plant.create(name: "Stromanthe Triostar", scientific_name: "Stromanthe sanguinea", family: "marantaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Stromanthe_Triostar.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882943", water_interval: 6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Sweetheart Plant", scientific_name: "Hoya kerrii", family: "succulent", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/sweetheartplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879848", water_interval: 12, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Sword Fern", scientific_name: "Polystichum munitum", family: "fern", light_level: "low" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/swordfern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882381", water_interval:  21, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Swiss Cheese Plant", scientific_name: "Monstera deliciosa", family: "araceae", light_level: "bright" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/swisscheeseplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390888228", water_interval: 12, rotate_interval: 12, soil_interval: 30)
Plant.create(name: "Ti plant", scientific_name: "Cordyline fruticosa", family: "	asparagaceae", light_level: "bright" , light_position: "direct", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Ti_plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875515", water_interval:  6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "UFO Plant", scientific_name: "Pilea peperomiodes", family: "urticaceae", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/UFO_plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875195", water_interval: 12, rotate_interval: 12, soil_interval: 0)
Plant.create(name: "Umbrella Tree", scientific_name: "Schefflera actinophylla", family: "araliaceae", light_level: "bright" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/umbrellatree.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887733", water_interval: 12, rotate_interval: 12, soil_interval: 30)
Plant.create(name: "Urn Plant", scientific_name: "Aechmea fasciata", family: "bromeliaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/UrnPlant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390883780", water_interval: 6, rotate_interval: 0, soil_interval: 6)
Plant.create(name: "Velvet Plant", scientific_name: "Gynura aurantiaca", family: "asteraceae", light_level: "bright" , light_position: "direct", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/velvetplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390877805", water_interval: 6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Warneckii Dracaena", scientific_name: "Dracaena deremensis", family: "asparagaceae", light_level: "low" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Warneckii_Dracaena.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390873790", water_interval: 6, rotate_interval: 6, soil_interval: 0)
Plant.create(name: "Watermelon Peperomia", scientific_name: "Peperomia argyreia", family: "piperaceae", light_level: "medium" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Watermelon_Peperomia.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879461", water_interval: 6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Wax Plant", scientific_name: "Hoya carnosa", family: "apocynaceae", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/waxplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882774", water_interval: 6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "Weeping Fig", scientific_name: "Ficus benjamina", family: "ficus", light_level: "bright" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/weepingfig.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675394814263", water_interval:  6, rotate_interval: 0, soil_interval: 6)
Plant.create(name: "Zebra Plant", scientific_name: "Haworthiopsis fasciata", family: "acanthaceae", light_level: "medium" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/zebraplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876933", water_interval: 6, rotate_interval: 0, soil_interval: 0)
Plant.create(name: "ZZ Plant", scientific_name: "Zamioculcas zamiifolia", family: "araceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/zzplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879502", water_interval:  15, rotate_interval: 15, soil_interval: 0)


puts "Plant people...👯‍♀️👯‍♂️"

3.times do
User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, dob: Faker::Date.birthday(min_age: 18, max_age: 65), 
street_address: Faker::Address.full_address, zipcode: Faker::Address.zip, username: "#{Faker::Lorem.word}", email: "#{Faker::Lorem.word}@gmail.com", password: "1234", phone_number: "818-383-9683")
end


puts "Gardening...🌱"

past_7_days = Date.today - 7

15.times do
    Garden.find_or_create_by(user: User.all.sample, plant: Plant.all.sample, previous_water_date: past_7_days, 
    previous_rotate_date: past_7_days, previous_soil_date: past_7_days)
end

puts 'Sending texts...📨'

3.times do
    Text.find_or_create_by(garden_id: Garden.all.sample, message: "Hey #{User.all.sample}, don't forget to water #{Plant.all.sample} today!")
end

puts "Seeding complete! 🌿"