# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Plant.destroy_all
User.destroy_all
Care.destroy_all
Text_sm.destroy_allcd ..
Reminders.destroy_all

puts "Seeding plants...🌱"

Plant.Create (common_name: "Airplant", scientific_name: "Tillandsia", type: "bromeliaceae", light_level: "bright", light_position: "indirect", size: "small", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/airplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887290") 
Plant.Create (common_name: "Alocasia", scientific_name: "Alocasia Macrorrhizos", type: "araceae", light_level: "bright", light_position: "indirect", size: "medium, large", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/alocasia.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875313")
Plant.Create (common_name: "Aloe", scientific_name: "Aloe vera", type: "succulent", light_level: "bright", light_position: "indirect", size: "small, medium", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/aloe.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875631")
Plant.Create (common_name: "Asparagus Fern", scientific_name: "Asparagus aethiopicus", type: "asparagaceae", light_level: "Medium", light_position:  "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/asparagusfern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675394815966")
Plant.Create (common_name: "Baby Jade", scientific_name: "Portulacaria afra", type: "succulent", light_level: "bright", light_position: "direct light", size: "small, medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/babyjade.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882980")
Plant.Create (common_name: "Banana Leaf Fig", scientific_name: "Ficus alii", type: "ficus", light_level: "bright", light_position:  "indirect", size: "large", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/bananaleaffig.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390884944")
Plant.Create (common_name: "Crispy Wave Fern", scientific_name: "Asplenium nidus", type: "fern", light_level: "medium", light_position: "indirect", size: "small, medium", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Crispy_Wave_Fern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390873774")
Plant.Create (common_name: "Bromeliad", scientific_name: "Guzmania Rana", type: "bromeliaceae", light_level: "bright", light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Bromeliad.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882668")
Plant.Create (common_name: "Boston Fern", scientific_name: "Nephrolepis exaltata", type: "fern", light_level: "bright", light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/bostonfern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390886288")
Plant.Create (common_name: "Burro's Tail", scientific_name: "Sedum morganianum", type: "succulent", light_level: "low", light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/burrowstail.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390873933")
Plant.Create (common_name: "Cast Iron Plant", scientific_name: "Aspidistra elatior", type: "asparagaceae", light_level: "low",light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Cast_Iron_Plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875830")
Plant.Create (common_name: "China Doll Plant", scientific_name: "Radermachera sinica", type: "evergreen", light_level: "low", light_position: "indirect", size: "small", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/chinadoll.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390877939")
Plant.Create (common_name: "Chinese Croton", scientific_name: "Excoecaria cochinchinensis", type: "euphorbias", light_level: "medium", light_position: "indirect", size: "large", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/chinesecroton.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390886908")
Plant.Create (common_name: "Corn Plant", scientific_name: "Dracaena fragrans", type: "asparagaceae,", light_level: "medium" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Corn_Plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390874676")
Plant.Create (common_name: "Creeping Fig", scientific_name: "Ficus pumila", type: "ficus", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Cast_Iron_Plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875830")
Plant.Create (common_name: "Gold Dust Croton", scientific_name: "Codiaeum variegatum", type: "euphorbiaceae", light_level: "low" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Gold_Dust_Croton.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879686")
Plant.Create (common_name: "Dragon Tree", scientific_name: "Dracaena marginata", type: "asparagaceae", light_level: "low" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/dragontree.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879250")
Plant.Create (common_name: "Dumb Cane", scientific_name: "Dieffenbachia", type: "araceae", light_level: "bright" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: true pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/dumbcane.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390874927")
Plant.Create (common_name: "Elephant Ear", scientific_name: "Caladium", type: "araceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/elephantear.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390878352")
Plant.Create (common_name: "Emerald Gem", scientific_name: "Homalomena", type: "araceae", light_level: "low" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/emeraldgem.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876244")
Plant.Create (common_name: "Emerald Ripple Peperomia", scientific_name: "Peperomia caperata", type: "piperaceae", light_level: "bright" , light_position: "indirect", size: "moderate", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/emeraldripple.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390877568")
Plant.Create (common_name: "Snake Plant", scientific_name: "Aglaonema", type: "araceae", light_level: "medium" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/snakeplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876407")
Plant.Create (common_name: "Eucalyptus", scientific_name: "Eucalyptus globulus", type: "aromatic", light_level: "low" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/eucalyptus.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390888612")
Plant.Create (common_name: "Fiddle Leaf Fig", scientific_name: "Ficus lyrata", type: "ficus", light_level: "bright" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Fiddle_Leaf_Fig.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390885484")
Plant.Create (common_name: "Fishbone Cactus", scientific_name: "Disocactus anguliger", type: "cactaceae", light_level: "low" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Fishbone_Cactus.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875112")
Plant.Create (common_name: "Fishtail Palm", scientific_name: "Caryota mitis", type: "arecaceae", light_level: "bright" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/fishtalepalm.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882065")
Plant.Create (common_name: "Fizzle Sizzle", scientific_name: "Albuca spiralis", type: "araceae", light_level: "bright" , light_position: "direct", size: "large", environment: "humid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/fizzlesizzle.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390883537")
Plant.Create (common_name: "Heart Leaf fern", scientific_name: "Hemionitis arifolia", type: "fern", light_level: "medium" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/heartleaffern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390877367")
Plant.Create (common_name: "Inchplant", scientific_name: "Tradescantia", type: "succulent", light_level: "medium" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/inchplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390883750")
Plant.Create (common_name: "Jade Plant", scientific_name: "Crassula ovata", type: "succulent", light_level: "medium" , light_position: "direct", size: "medium", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/jadeplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887543")
Plant.Create (common_name: "Lucky Bamboo", scientific_name: "Dracaena sanderiana", type: "asparagaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/luckybamboo.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390874438")
Plant.Create (common_name: "Maidenhair", scientific_name: "Adiantum", type: "fern", light_level: "medium" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/maidenhair.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390886631")
Plant.Create (common_name: "Money Tree", scientific_name: "Pachira aquatica", type: "malvaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Moneytree.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390880925")
Plant.Create (common_name: "Nerve Plant", scientific_name: "Fittonia albivenis", type:"acanthaceae", light_level: "low" , light_position: "direct", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/nerveplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390888722")
Plant.Create (common_name: "Paddle Plant", scientific_name: "Kalanchoe thyrsiflora", type: "succulent", light_level: "bright" , light_position: "direct", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/paddleplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390873861")
Plant.Create (common_name: "Parlor Palm", scientific_name: "Chamaedorea elegans", type: "arecaceae", light_level: "medium" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Parlorpalm.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390890058")
Plant.Create (common_name: "Peace Lily", scientific_name: "Pilea involucrata", type: "araceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/peacelily.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390881652")
Plant.Create (common_name: "Peacock Plant", scientific_name: "Calathea makoyana", type: "marantaceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/peacockplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390885037")
Plant.Create (common_name: "Persian shield", scientific_name: "Stobilanthes dyerianus", type: "acanthaceae", light_level: "bright" , light_position: "direct", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/persiansheild.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390885802")
Plant.Create (common_name: "Philodendron", scientific_name: "Pilea involucrata", type: "araceae", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/philodendron.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887571")
Plant.Create (common_name: "Polka Dot Begonia", scientific_name: "Begonia maculata", type: "begoniaceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Polka_Dot_Begonia.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390881610")
Plant.Create (common_name: "Ponytail Palm", scientific_name: "Beaucarnea Recurvata", type: "asparagaceae", light_level: "bright" , light_position: "direct", size: "large", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/ponytailpalm.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390874575")
Plant.Create (common_name: "Pothos", scientific_name: "Epipremnum aureum", type: "araceae", light_level: "bright" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/pothos.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887736")
Plant.Create (common_name: "Prayer Plant", scientific_name: "Oxalis", type: "oxalidaceae", light_level: "medium" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/prayerplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390889578")
Plant.Create (common_name: "Purple Shamrock", scientific_name: "Pilea involucrata", type: "urticaceae", light_level: "medium" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/purpleshamrock.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675394814490")
Plant.Create (common_name: "Rabbit's Foot Fern", scientific_name: "Davallia fejeensis", type: "fern", light_level: "bright" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/rabbitsfootfern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876158")
Plant.Create (common_name: "Red Aglaonema", scientific_name: " Aglaonema commutatum", type: "araceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Red_Aglaonema.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390888161")
Plant.Create (common_name: "Silver Dollar Vine", scientific_name: "Xerosicyos danguyi", type: "succulent", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/silverdollarvine.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675394814090")
Plant.Create (common_name: "Spider Plant", scientific_name: "Chlorophytum comosum", type: "asparagaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/spiderplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876846")
Plant.Create (common_name: "Shingle Plant", scientific_name: "Rhaphidophora hayi", type: "araceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/shingleplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390890147")
Plant.Create (common_name: "Staghorn Fern", scientific_name: "Platycerium ", type: "polypodiaceae", light_level: "bright" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/staghornfern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390884256")
Plant.Create (common_name: "String of Bananas", scientific_name: "Curio radicans", type: "succulent", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/stringofbananas.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390881107")
Plant.Create (common_name: "String of Dolphins", scientific_name: "Senecio peregrinus", type: "succulent", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/stringofdolphins.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879959")
Plant.Create (common_name: "String of Pearls", scientific_name: "Senecio rowleyanus", type: "succulent", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Stringofpearls.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390890401")
Plant.Create (common_name: "String of Turtles", scientific_name: "Peperomia prostrata", type: "succulent", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/stringofturtles.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887425")
Plant.Create (common_name: "Stromanthe Triostar", scientific_name: "Stromanthe sanguinea", type: "marantaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Stromanthe_Triostar.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882943")
Plant.Create (common_name: "Sweetheart Plant", scientific_name: "Hoya kerrii", type: "succulent", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/sweetheartplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879848")
Plant.Create (common_name: "Sword Fern", scientific_name: "Polystichum munitum", type: "fern", light_level: "low" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/swordfern.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882381")
Plant.Create (common_name: "Swiss Cheese Plant", scientific_name: "Monstera deliciosa", type: "araceae", light_level: "bright" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/swisscheeseplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390888228")
Plant.Create (common_name: "Ti plant", scientific_name: "Cordyline fruticosa", type: "	asparagaceae", light_level: "bright" , light_position: "direct", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Ti_plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875515")
Plant.Create (common_name: "UFO Plant", scientific_name: "Pilea peperomiodes", type: "urticaceae", light_level: "bright" , light_position: "direct", size: "small", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/UFO_plant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390875195")
Plant.Create (common_name: "Umbrella Tree", scientific_name: "Schefflera actinophylla", type: "araliaceae", light_level: "bright" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/umbrellatree.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390887733")
Plant.Create (common_name: "Urn Plant", scientific_name: "Aechmea fasciata", type: "bromeliaceae", light_level: "bright" , light_position: "indirect", size: "medium", environment: "arid", kid_friendly: false, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/UrnPlant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390883780")
Plant.Create (common_name: "Velvet Plant", scientific_name: "Gynura aurantiaca", type: "asteraceae", light_level: "bright" , light_position: "direct", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/velvetplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390877805")
Plant.Create (common_name: "Warneckii Dracaena", scientific_name: "Dracaena deremensis", type: "asparagaceae", light_level: "low" , light_position: "indirect", size: "large", environment: "humid", kid_friendly: true, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Warneckii_Dracaena.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390873790")
Plant.Create (common_name: "Watermelon Peperomia", scientific_name: "Peperomia argyreia", type: "piperaceae", light_level: "medium" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/Watermelon_Peperomia.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879461")
Plant.Create (common_name: "Wax Plant", scientific_name: "Hoya carnosa", type: "apocynaceae", light_level: "low" , light_position: "indirect", size: "small", environment: "arid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/waxplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390882774")
Plant.Create (common_name: "Weeping Fig", scientific_name: "Ficus benjamina", type: "ficus", light_level: "bright" , light_position: "indirect", size: "large", environment: "arid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/weepingfig.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675394814263")
Plant.Create (common_name: "Zebra Plant", scientific_name: "Haworthiopsis fasciata", type: "acanthaceae", light_level: "medium" , light_position: "indirect", size: "small", environment: "humid", kid_friendly: true, pet_friendly: true, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/zebraplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390876933")
Plant.Create (common_name: "ZZ Plant", scientific_name: "Zamioculcas zamiifolia", type: "araceae", light_level: "medium" , light_position: "indirect", size: "medium", environment: "humid", kid_friendly: false, pet_friendly: false, image: "https://ik.imagekit.io/dbmvg03cg/Sprout/zzplant.png?ik-sdk-version=javascript-1.4.3&updatedAt=1675390879502")


puts "Plantcare...❤️"

Care.create(type: "water")
Care.create(type: "prune")
Care.create(type: "rotate")
Care.create(type: "repot")

puts "Plant people...👯‍♀️👯‍♂️"

3.times do
    User.find_or_create_by(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, dob: Faker::Date.birthday(min_age: 18, max_age: 65), 
    street_address: Faker::Address.full_addres, zipcode: Faker::Address.zip, username: "#{Faker::Lorem.word}@gmail.com", phone_number: "818-383-9683")
end

puts "Scheduling reminders...📆"

5.times do 
    Reminder.find_or_create_by(user: User.all.sample, plant: Plant.all.sample, start: Time.now, end: Time.now + (30).minutes)
end

5.times do
    Text_sm.find_or_create_by(message:"Hey #{User.all.sample}, don't forgot to #{Care.all.sample} #{Plant.all.sample}")








